DROP TABLE IF EXISTS food_items CASCADE;

CREATE TABLE food_items (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR(255) NOT NULL,
  category VARCHAR(255) NOT NULL,
  cost SMALLINT NOT NULL,
  description TEXT,
  photo_url VARCHAR(255) NOT NULL,
  availability BOOLEAN DEFAULT TRUE
  );
